# Generated by Django 3.0.6 on 2020-07-15 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='budget',
        ),
    ]
