# Generated by Django 3.0.6 on 2020-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_trip_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
