# Generated by Django 3.0.6 on 2020-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_trip_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
